---

use_my_public_key:          true
my_public_key_file:         ".ssh/id_rsa.pub"

cloud_init_profile:         "basic"

# etcd cluster discovery token

use_discovery_token:        true
request_discovery_url:      https://discovery.etcd.io/new
default_discovery_url:      https://discovery.etcd.io

# obtain discovery token from https://discovery.etcd.io/new
discovery_token:            ""

# or provide one via playbook variable
# discovery_token:            "your-token-here"